class PrefectureType < ActiveHash::Base
  include ActiveHash::Enum
  
  self.data = [
{code: '01', pname: 'HOKKAIDO', name: '北海道'},
{code: '02', pname: 'AOMORI', name: '青森県'},
{code: '03', pname: 'IWATE', name: '岩手県'},
{code: '04', pname: 'MIYAGI', name: '宮城県'},
{code: '05', pname: 'AKITA', name: '秋田県'},
{code: '06', pname: 'YAMAGATA', name: '山形県'},
{code: '07', pname: 'FUKUSHIMA', name: '福島県'},
{code: '08', pname: 'IBARAKI', name: '茨城県'},
{code: '09', pname: 'TOCHIGI', name: '栃木県'},
{code: '10', pname: 'GUNMA', name: '群馬県'},
{code: '11', pname: 'SAITAMA', name: '埼玉県'},
{code: '12', pname: 'CHIBA', name: '千葉県'},
{code: '13', pname: 'TOKYO', name: '東京都'},
{code: '14', pname: 'KANAGAWA', name: '神奈川県'},
{code: '15', pname: 'NIIGATA', name: '新潟県'},
{code: '16', pname: 'TOYAMA', name: '富山県'},
{code: '17', pname: 'ISHIKAWA', name: '石川県'},
{code: '18', pname: 'FUKUI', name: '福井県'},
{code: '19', pname: 'YAMANASHI', name: '山梨県'},
{code: '20', pname: 'NAGANO', name: '長野県'},
{code: '21', pname: 'GIHU', name: '岐阜県'},
{code: '22', pname: 'SHIZUOKA', name: '静岡県'},
{code: '23', pname: 'AICHI', name: '愛知県'},
{code: '24', pname: 'MIE', name: '三重県'},
{code: '25', pname: 'SHIGA', name: '滋賀県'},
{code: '26', pname: 'KYOTO', name: '京都府'},
{code: '27', pname: 'OHSAKA', name: '大阪府'},
{code: '28', pname: 'HYOGO', name: '兵庫県'},
{code: '29', pname: 'NARA', name: '奈良県'},
{code: '30', pname: 'WAKAYAMA', name: '和歌山県'},
{code: '31', pname: 'TOTTORI', name: '鳥取県'},
{code: '32', pname: 'SHIMANE', name: '島根県'},
{code: '33', pname: 'OKAYAMA', name: '岡山県'},
{code: '34', pname: 'HIROSHIMA', name: '広島県'},
{code: '35', pname: 'YAMAGUCHI', name: '山口県'},
{code: '36', pname: 'TOKUSHIMA', name: '徳島県'},
{code: '37', pname: 'KAGAWA', name: '香川県'},
{code: '38', pname: 'EHIME', name: '愛媛県'},
{code: '39', pname: 'KOUCHI', name: '高知県'},
{code: '40', pname: 'FUKUOKA', name: '福岡県'},
{code: '41', pname: 'SAGA', name: '佐賀県'},
{code: '42', pname: 'NAGASAKI', name: '長崎県'},
{code: '43', pname: 'KUMAMOTO', name: '熊本県'},
{code: '44', pname: 'OHITA', name: '大分県'},
{code: '45', pname: 'MIYAZAKI', name: '宮崎県'},
{code: '46', pname: 'KAGOSHIMA', name: '鹿児島県'},
{code: '47', pname: 'OKINAWA', name: '沖縄県'},
  ]

  enum_accessor :prefecture_type
end
